name: 'movebase_planner'

ros_launch:
  mode: test
  name: ${name}
  wait: 30

  test:
    common: "roslaunch base_navigation move_base.launch use_map:=true base:=kobuki"

algorithm:
  _target_: pyrobot.algorithms.base_planning_impl.movebase_planner.MovebasePlanner

robot_labels: ['locobot']

conf:
  PLAN_TOPIC: "/move_base/GlobalPlanner/make_plan"
  PLAN_TOL: 0.1
  MAP_FRAME: "map"
  BASE_FRAME: "/base_link"
  TRACKED_POINT: 8
  TRESHOLD_LIN: 0.15

dependencies:
  - algorithm: 'ilqr_control'
