
name: 'franka' # This is fixed!


# TODO: to be filled by ros-control manager
ros_launch:
  mode: realrobot
  name: ${name}
  wait: 30
  habitat:
    common: null
    arm: null
    base: null
    camera: null

  realrobot:
    common: 'roslaunch franka_interface interface.launch robot_ip:=172.16.0.2 load_gripper:=true'
    arm: null
    base: null
    camera: null


# Common contains all the commonly shared objects
common: null

modules:

  - object:
      _target_: pyrobot.robots.franka.arm.FrankaArm
      # params: 
    ns: ''
    transform:
      use_udf: True 
      position: null
      rotation: null
      frame: null
    name : 'arm'
    conf: 
      # ARM class name
      CLASS : "FrankaArm"
      # robot description parameter name for the arm
      ARM_ROBOT_DSP_PARAM_NAME : "/robot_description"

      MOVEGROUP_NAME: "panda_arm"
      # base frame for the arm
      ARM_BASE_FRAME : "panda_link0"
      # end-effector frame of the arm
      EE_FRAME : "panda_hand"
      # joint states topic name for the arm
      ROSTOPIC_JOINT_STATES : "/joint_states"

      JOINT_NAMES: [panda_joint1, panda_joint2, panda_joint3, panda_joint4, panda_joint5, panda_joint6, panda_joint7]

      NEUTRAL_POSE: [-0.017792060227770554, -0.7601235411041661, 0.019782607023391807, -2.342050140544315, 0.029840531355804868, 1.5411935298621688, 0.7534486589746342]

      JOINT_VELOCITY_LIMITS: [2.1750, 2.1750, 2.1750, 2.1750, 2.6100, 2.6100, 2.6100]

  - object:
      _target_: pyrobot.robots.franka.gripper.FrankaGripper
      # params: 
    ns: ''
    transform:
      use_udf: True 
      position: null
      rotation: null
      frame: null
    name : 'gripper'
    conf:
      # GRIPPER class name
      CLASS: "FrankaGripper"
